### ISSUE TITLE
Payload validation

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/u-bahn-api#12]
When posting in the following payload to the `/users` endpoint

```
{
    "handle": "lazybaer",
    "firstname": "Christopher",
    "lastname": "DeLaurentis"
}
```

there doesn't seem to be validation on the payload keys. Checking in the QLDB it seems that the uncapitalized/uncamel-cased fields were added instead of rejecting the payload. I haven't checked but this might be the case on other endpoints.

![image](https://user-images.githubusercontent.com/1504607/84443061-e03e8480-ac0c-11ea-9950-8f59911b206b.png)

**Comment by callmekatootie** [comment]
@cwdcwd This is now resolved. Please let me know if you are not getting any validation errors with any request.

**Comment by callmekatootie** [comment]
Correction - NOT FIXED. Had to undo the fix.

Discovered a side effect of the change so reverted it. Issue still exists.

**Comment by callmekatootie** [comment]
This is now resolved
