### ISSUE TITLE
Roles - Single role or multiple

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#3]
@cwdcwd Are the roles on a user single or multiple? The ERD has them as singular, but, comparing it with what we have at Topcoder, it could be multiple too.

If it's singular it is fine - the api needs to be updated to return the single object. However, if it is multiple, then how would:
- We show it in the UI
![image](https://user-images.githubusercontent.com/2317133/83863303-c995ba80-a740-11ea-81fe-61c1572e6708.png)

- We carry out the update to the role, since UI has it as a single field
![image](https://user-images.githubusercontent.com/2317133/83863253-b84cae00-a740-11ea-9b17-a985e3d5a581.png)

**Comment by cwdcwd** [comment]
the roles are multiple in the JWT. I might have mislabelled the crows-feet on the ERD. 
Regardless, I think _this_ `role` in the UI is more of a `Title`, coming from an attribute than an actual platform `Role`. Does that make sense?

**Comment by callmekatootie** [comment]
It does. What should I go with for our use case? 1 role or multiple? And if multiple, how should the updates happen considering how the UI is currently...

**Comment by cwdcwd** [comment]
Updating this `role` updates the attribute value. 
For _actual_ platform `Roles`, they're not related to the UI and don't show up there.

**Comment by callmekatootie** [comment]
_Ah._ Makes sense

**Comment by callmekatootie** [comment]
Closing. Role has been integrated.
