### ISSUE TITLE
[Finalized] Groups: Filters

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#5]
### Question 1

@cwdcwd For the filter users by the group feature, which api should be called? Or rather, considering that the groups are in the `/v5/groups` api and the users are in ubahn, how do we filter users by a specific group

**Comment by cwdcwd** [comment]
@callmekatootie there should be a call for the members in a group on the `v5/groups` API.

**Comment by cwdcwd** [comment]
CC @dushyantb

**Comment by callmekatootie** [comment]
@cwdcwd There indeed is a GET `/groups/{groupdId}/members`. Assuming I call this, I get the list of members belonging to that group (paginated). I would then need to query ES for each user to get their enriched user details in our backend API. Is that approach right?

**Comment by callmekatootie** [comment]
Discussed on slack.

- UI calls GET /groups/{groupId}/members. 
- UI will then call Ubahn API for EACH user returned by the groups api to get the user's details.
- In the returned members from groups, there will be a yet-to-be-added attribute called `universalUID` which will be the Ubahn user id of that member. Use this to GET `/users/{universalUID}?enrich=true` to get details of each user and display it on the UI...

**Comment by callmekatootie** [comment]
This is now in
