### ISSUE TITLE
Groups: Add user to group

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#6]
### Question 1

@cwdcwd In order to add a user to a group, I assume:
- We call POST /v5/groups/{groupId}/members
- The request body would be:

```
{
  "memberId": // the user id
  "membershipType": "user" // constant
}
```

Is that correct?

**Comment by cwdcwd** [comment]
I believe that's correct, right @dushyantb ?

**Comment by dushyantb** [comment]
this is correct

**Comment by cwdcwd** [comment]
@callmekatootie pursuant to our conversation on slack, @dushyantb is going to add a field to represent the u-bahn userId as the `memberId` here is the TC userId and not our universal identity user

**Comment by callmekatootie** [comment]
This is now in
