### ISSUE TITLE
[Finalized] Groups: Get groups that belong to a user

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#7]
### Question 1

![image](https://user-images.githubusercontent.com/2317133/83968145-bfacbc80-a8e4-11ea-9834-fe5d367f4c74.png)

@cwdcwd Referring to the display of the groups that a user belongs to. When we get the list of users from Elasticsearch, should we loop over the users (in the API itself and not UI) to get the groups for that user or some other approach?

If the former is correct approach, then would the api that gives us the groups for a specific user (and not the user making the request) be GET `/v5/groups?memberId={userID}` be the correct api to call? (Is `memberId` the correct query parameter to use).

**Comment by cwdcwd** [comment]
I believe that's the correct endpoint, right @dushyantb ?

**Comment by dushyantb** [comment]
@callmekatootie you can directly use the `v5/groups/memberGroups/:memberId` endpoint to get the groups where the user belongs.

**Comment by callmekatootie** [comment]
Thanks @dushyantb .

@cwdcwd Does this mean that, once we get the users from ES, we loop through each of them to get their groups?

**Comment by cwdcwd** [comment]
@callmekatootie good question. It probably makes sense for the UI to handle it as it can call with an M2M token for administrative access

**Comment by callmekatootie** [comment]
Got it.

- Call UBahn API
- UBahn API will get the users. But before it responds, for **each user** it will then query groups api at GET `/v5/groups/memberGroups/:memberId` to get the groups for that member
- Once it has it, it will send the response

**Comment by callmekatootie** [comment]
This is now in
