### ISSUE TITLE
[Finalized] Groups: Filters - Numbers

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#8]
## Question 1

![image](https://user-images.githubusercontent.com/2317133/83970586-0d7cf100-a8f4-11ea-80b0-8dd4e52421e2.png)

@cwdcwd What are the numbers next to the group names.

**Comment by wdprice** [comment]
Count of members in the group

**Comment by callmekatootie** [comment]
### Question 2

So this would mean that we need to:

**Comment by callmekatootie** [comment]
### Question 2

So this would mean:
1. We need to get groups that the user is part of
2. We need to get groups that the user is not part of but can be (groups in the same org)
3. Count of members in each group

For 3, it sounds like we need to run a batch job and store that info in redis perhaps... And this batch job would have to be in the groups api... Or is there a better approach?

**Comment by cwdcwd** [comment]
you could probably loop all the groups in the org and take their totals count from the headers. Then call for the groups specific to the user to separate them out. Adding @dushyantb for alternative ideas

**Comment by dushyantb** [comment]
we are already having API to get the memberCounts in specific group `/groups/:groupId/membersCount`; we can modify the API to get the counts and groupId based on the organisationId

and filter out the groupIds based on the list got from point 1

**Comment by cwdcwd** [comment]
@callmekatootie , @dushyantb is going to also add a filter param for `organizationId` so that you can get all the groups and counts in one call

**Comment by callmekatootie** [comment]
As per discussion on slack, I will proceed with the assumption that GET /groups will return with the count along with the other details returned currently (under the `count` attribute).

For My Groups, I will call GET `/groups`
For Other Groups, I will call GET `/groups?organizationId=the_user_org_id` and then filter the groups that already exist under My Groups. The user org id needs to be first fetched from UBahn for the user.
