### ISSUE TITLE
[Finalized] Skills: Filters

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-api#9]
@cwdcwd So - the skills that will be added to users would be coming from EMSI.

Thus, it would make sense to have the skills listed under the filters to also come from EMSI.

However, to list all the skills from EMSI (to filter) would not make sense since it has a lot of skills. How thus to display the skills from EMSI under the filter?

cc @wdprice

**Comment by cwdcwd** [comment]
I believe, and @wdprice can correct me, we want to autocomplete on skills so we would broker a call to EMSI through our back end

**Comment by callmekatootie** [comment]
Ok. For the filter, I will have the user search for skills in EMSI instead of selecting from existing pills... The skill that the user selects will show up as a pill that the user can remove

**Comment by callmekatootie** [comment]
This is now in
